[Ad-Urls]
#Hagezi = https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/light-onlydomains.txt
#Adguard = https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
#Oisd = https://small.oisd.nl/domainswild2
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/multi-onlydomains.txt
